name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install protobuf compiler
      shell: bash
      run: |
        mkdir -p $HOME/d/protoc
        cd $HOME/d/protoc
        export PROTO_ZIP="protoc-21.4-linux-x86_64.zip"
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.4/$PROTO_ZIP
        unzip $PROTO_ZIP
        export PATH=$PATH:$HOME/d/protoc/bin
        protoc --version    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
